server:
  port: 8081
  address: 0.0.0.0
  ssl:
    enabled: false

spring:
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        register: true
        health-check-path: /actuator/health
        health-check-interval: 10s
        hostname: ${spring.application.name}
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: user_admin
    password: root_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: naisha2106

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha

jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    com.example.auth_service: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    gateway:
      enabled: true