server:
    port: 8082

jwt:
    secret: ${JWT_SECRET}
spring:
    cloud:
        consul:
            host: consul
            port: 8500
            discovery:
                register: true
                health-check-path: /actuator/health
                health-check-interval: 10s
                hostname: ${spring.application.name}
    application:
        name: wallet-service
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri:
    rabbitmq:
        host: rabbitmq
        port: 5672
        username: admin
        password: admin123
        listener:
            simple:
                default-requeue-rejected: false
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always