server:
    port: 8082
    ssl:
        key-store: file:/app/certs/wallet.p12
        key-store-password: ${SSL_PASSWORD}
        key-store-type: PKCS12
        trust-store: file:/app/certs/truststore.p12
        trust-store-password: ${SSL_TRUST_STORE_PASSWORD}
        trust-store-type: PKCS12
        client-auth: want
jwt:
    secret: ${JWT_SECRET}
spring:
    cloud:
        consul:
            host: consul
            port: 8500
            discovery:
                register: true
                scheme: https
                health-check-url: https://wallet-service:8082/actuator/health
                health-check-tls-skip-verify: true
    application:
        name: wallet-service
    rabbitmq:
        host: rabbitmq
        port: 5672
        username: admin
        password: admin123
        listener:
            simple:
                default-requeue-rejected: false
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
    tracing:
        sampling:
            probability: 1.0
        propagation:
            type: b3
        export:
            zipkin:
                endpoint: http://zipkin:9411/api/v2/spans  
    
    endpoints:
        web:
            exposure:
                include: health,info,metrics,prometheus
    endpoint:
        health:
            show-details: always
    prometheus:
        metrics:
            export:
                enabled: true
logging:
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}]"  # 👈 logs con traceId
