server:
  port: 8084

spring:
  application:
    name: ledger-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://ledger-db:5432/ledger_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:admin}
    password: ${SPRING_RABBITMQ_PASSWORD:naisha2106}
  cloud:
    consul:
      host: ${SPRING_CLOUD_CONSUL_HOST:consul}
      port: ${SPRING_CLOUD_CONSUL_PORT:8500}
      discovery:
        register: true
        scheme: http
        health-check-path: ledger-service:8084/actuator/health
        health-check-interval: 10s
logging:
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}]"  # 👈 logs con traceId

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: b3
    export:
      zipkin:
        endpoint: http://zipkin:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: health,info, prometheus
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true